pub mod buy_card;
pub mod cancel_listing;
pub mod claim_match_card;
pub mod create_group;
pub mod distribute_prize;
pub mod initialize_collection_state;
pub mod initialize_tree_state;
pub mod join_group;
pub mod list_for_sale;
pub mod pause_group;
pub mod settle_prediction;
pub mod submit_predictions;

// Glob re-exports so `#[program]` can resolve Context structs and the hidden
// `__client_accounts_*` modules generated by `#[derive(Accounts)]`. Handler
// free-functions were renamed from `handler` to `<ix>_handler` so the glob
// re-exports no longer collide — dropping the previous
// `#[allow(ambiguous_glob_reexports)]` annotations.
pub use buy_card::*;
pub use cancel_listing::*;
pub use claim_match_card::*;
pub use create_group::*;
pub use distribute_prize::*;
pub use initialize_collection_state::*;
pub use initialize_tree_state::*;
pub use join_group::*;
pub use list_for_sale::*;
pub use pause_group::*;
pub use settle_prediction::*;
pub use submit_predictions::*;
