/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketIndexRouteImport } from './routes/market/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as FixturesIndexRouteImport } from './routes/fixtures/index'
import { Route as ProfileWalletRouteImport } from './routes/profile.$wallet'
import { Route as MarketListRouteImport } from './routes/market/list'
import { Route as MarketListingPdaRouteImport } from './routes/market/$listingPda'
import { Route as GroupsGroupPdaRouteImport } from './routes/groups/$groupPda'
import { Route as FixturesFixtureIdRouteImport } from './routes/fixtures/$fixtureId'
import { Route as FixturesFixtureIdIndexRouteImport } from './routes/fixtures/$fixtureId/index'
import { Route as FixturesFixtureIdPredictRouteImport } from './routes/fixtures/$fixtureId/predict'
import { Route as FixturesFixtureIdLiveRouteImport } from './routes/fixtures/$fixtureId/live'

const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesIndexRoute = FixturesIndexRouteImport.update({
  id: '/fixtures/',
  path: '/fixtures/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWalletRoute = ProfileWalletRouteImport.update({
  id: '/profile/$wallet',
  path: '/profile/$wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketListRoute = MarketListRouteImport.update({
  id: '/market/list',
  path: '/market/list',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketListingPdaRoute = MarketListingPdaRouteImport.update({
  id: '/market/$listingPda',
  path: '/market/$listingPda',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupPdaRoute = GroupsGroupPdaRouteImport.update({
  id: '/groups/$groupPda',
  path: '/groups/$groupPda',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesFixtureIdRoute = FixturesFixtureIdRouteImport.update({
  id: '/fixtures/$fixtureId',
  path: '/fixtures/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesFixtureIdIndexRoute = FixturesFixtureIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FixturesFixtureIdRoute,
} as any)
const FixturesFixtureIdPredictRoute =
  FixturesFixtureIdPredictRouteImport.update({
    id: '/predict',
    path: '/predict',
    getParentRoute: () => FixturesFixtureIdRoute,
  } as any)
const FixturesFixtureIdLiveRoute = FixturesFixtureIdLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => FixturesFixtureIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/docs': typeof DocsRoute
  '/style-guide': typeof StyleGuideRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRouteWithChildren
  '/groups/$groupPda': typeof GroupsGroupPdaRoute
  '/market/$listingPda': typeof MarketListingPdaRoute
  '/market/list': typeof MarketListRoute
  '/profile/$wallet': typeof ProfileWalletRoute
  '/fixtures': typeof FixturesIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/market': typeof MarketIndexRoute
  '/fixtures/$fixtureId/live': typeof FixturesFixtureIdLiveRoute
  '/fixtures/$fixtureId/predict': typeof FixturesFixtureIdPredictRoute
  '/fixtures/$fixtureId/': typeof FixturesFixtureIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/docs': typeof DocsRoute
  '/style-guide': typeof StyleGuideRoute
  '/groups/$groupPda': typeof GroupsGroupPdaRoute
  '/market/$listingPda': typeof MarketListingPdaRoute
  '/market/list': typeof MarketListRoute
  '/profile/$wallet': typeof ProfileWalletRoute
  '/fixtures': typeof FixturesIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/market': typeof MarketIndexRoute
  '/fixtures/$fixtureId/live': typeof FixturesFixtureIdLiveRoute
  '/fixtures/$fixtureId/predict': typeof FixturesFixtureIdPredictRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/docs': typeof DocsRoute
  '/style-guide': typeof StyleGuideRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRouteWithChildren
  '/groups/$groupPda': typeof GroupsGroupPdaRoute
  '/market/$listingPda': typeof MarketListingPdaRoute
  '/market/list': typeof MarketListRoute
  '/profile/$wallet': typeof ProfileWalletRoute
  '/fixtures/': typeof FixturesIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/market/': typeof MarketIndexRoute
  '/fixtures/$fixtureId/live': typeof FixturesFixtureIdLiveRoute
  '/fixtures/$fixtureId/predict': typeof FixturesFixtureIdPredictRoute
  '/fixtures/$fixtureId/': typeof FixturesFixtureIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album'
    | '/docs'
    | '/style-guide'
    | '/fixtures/$fixtureId'
    | '/groups/$groupPda'
    | '/market/$listingPda'
    | '/market/list'
    | '/profile/$wallet'
    | '/fixtures'
    | '/groups'
    | '/market'
    | '/fixtures/$fixtureId/live'
    | '/fixtures/$fixtureId/predict'
    | '/fixtures/$fixtureId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album'
    | '/docs'
    | '/style-guide'
    | '/groups/$groupPda'
    | '/market/$listingPda'
    | '/market/list'
    | '/profile/$wallet'
    | '/fixtures'
    | '/groups'
    | '/market'
    | '/fixtures/$fixtureId/live'
    | '/fixtures/$fixtureId/predict'
    | '/fixtures/$fixtureId'
  id:
    | '__root__'
    | '/'
    | '/album'
    | '/docs'
    | '/style-guide'
    | '/fixtures/$fixtureId'
    | '/groups/$groupPda'
    | '/market/$listingPda'
    | '/market/list'
    | '/profile/$wallet'
    | '/fixtures/'
    | '/groups/'
    | '/market/'
    | '/fixtures/$fixtureId/live'
    | '/fixtures/$fixtureId/predict'
    | '/fixtures/$fixtureId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRoute
  DocsRoute: typeof DocsRoute
  StyleGuideRoute: typeof StyleGuideRoute
  FixturesFixtureIdRoute: typeof FixturesFixtureIdRouteWithChildren
  GroupsGroupPdaRoute: typeof GroupsGroupPdaRoute
  MarketListingPdaRoute: typeof MarketListingPdaRoute
  MarketListRoute: typeof MarketListRoute
  ProfileWalletRoute: typeof ProfileWalletRoute
  FixturesIndexRoute: typeof FixturesIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  MarketIndexRoute: typeof MarketIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/': {
      id: '/fixtures/'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$wallet': {
      id: '/profile/$wallet'
      path: '/profile/$wallet'
      fullPath: '/profile/$wallet'
      preLoaderRoute: typeof ProfileWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/list': {
      id: '/market/list'
      path: '/market/list'
      fullPath: '/market/list'
      preLoaderRoute: typeof MarketListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$listingPda': {
      id: '/market/$listingPda'
      path: '/market/$listingPda'
      fullPath: '/market/$listingPda'
      preLoaderRoute: typeof MarketListingPdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupPda': {
      id: '/groups/$groupPda'
      path: '/groups/$groupPda'
      fullPath: '/groups/$groupPda'
      preLoaderRoute: typeof GroupsGroupPdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId': {
      id: '/fixtures/$fixtureId'
      path: '/fixtures/$fixtureId'
      fullPath: '/fixtures/$fixtureId'
      preLoaderRoute: typeof FixturesFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId/': {
      id: '/fixtures/$fixtureId/'
      path: '/'
      fullPath: '/fixtures/$fixtureId/'
      preLoaderRoute: typeof FixturesFixtureIdIndexRouteImport
      parentRoute: typeof FixturesFixtureIdRoute
    }
    '/fixtures/$fixtureId/predict': {
      id: '/fixtures/$fixtureId/predict'
      path: '/predict'
      fullPath: '/fixtures/$fixtureId/predict'
      preLoaderRoute: typeof FixturesFixtureIdPredictRouteImport
      parentRoute: typeof FixturesFixtureIdRoute
    }
    '/fixtures/$fixtureId/live': {
      id: '/fixtures/$fixtureId/live'
      path: '/live'
      fullPath: '/fixtures/$fixtureId/live'
      preLoaderRoute: typeof FixturesFixtureIdLiveRouteImport
      parentRoute: typeof FixturesFixtureIdRoute
    }
  }
}

interface FixturesFixtureIdRouteChildren {
  FixturesFixtureIdLiveRoute: typeof FixturesFixtureIdLiveRoute
  FixturesFixtureIdPredictRoute: typeof FixturesFixtureIdPredictRoute
  FixturesFixtureIdIndexRoute: typeof FixturesFixtureIdIndexRoute
}

const FixturesFixtureIdRouteChildren: FixturesFixtureIdRouteChildren = {
  FixturesFixtureIdLiveRoute: FixturesFixtureIdLiveRoute,
  FixturesFixtureIdPredictRoute: FixturesFixtureIdPredictRoute,
  FixturesFixtureIdIndexRoute: FixturesFixtureIdIndexRoute,
}

const FixturesFixtureIdRouteWithChildren =
  FixturesFixtureIdRoute._addFileChildren(FixturesFixtureIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRoute,
  DocsRoute: DocsRoute,
  StyleGuideRoute: StyleGuideRoute,
  FixturesFixtureIdRoute: FixturesFixtureIdRouteWithChildren,
  GroupsGroupPdaRoute: GroupsGroupPdaRoute,
  MarketListingPdaRoute: MarketListingPdaRoute,
  MarketListRoute: MarketListRoute,
  ProfileWalletRoute: ProfileWalletRoute,
  FixturesIndexRoute: FixturesIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  MarketIndexRoute: MarketIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
